export const motivationalPhrases = [
  "Small steps every day lead to big achievements.",
  "Progress starts with consistency.",
  "Your future is built one task at a time.",
  "Keep showing up for your goals.",
  "Discipline creates freedom.",
  "Great things take time and persistence.",
  "Focus on progress, not perfection.",
  "Every completed task moves you forward.",
  "Growth happens outside your comfort zone.",
  "Stay patient. Stay consistent.",
  "One productive day can change everything.",
  "Build habits that build your future.",
  "Small actions create powerful results.",
  "Keep learning. Keep improving.",
  "Your goals deserve your effort today.",
  "Success is built through repetition.",
  "Start now. Adjust later.",
  "Every expert started as a beginner.",
  "Momentum is created through action.",
  "Progress compounds over time.",
  "Believe in the power of daily effort.",
  "Consistency beats motivation.",
  "One hour today is an investment in tomorrow.",
  "Turn ideas into achievements.",
  "Stay committed to your vision.",
  "Hard days still count.",
  "Learn something today your future self will thank you for.",
  "Keep moving, even slowly.",
  "Action creates clarity.",
  "Improvement starts with one decision.",
  "You are closer than you think.",
  "The journey matters as much as the goal.",
  "Make today productive.",
  "Build the life you imagine.",
  "Stay focused on what matters most.",
  "Progress is progress, no matter how small.",
  "Keep investing in yourself.",
  "Success grows from discipline.",
  "Show yourself what you’re capable of.",
  "Create momentum through daily action.",
  "Your effort today shapes your tomorrow.",
  "Done is better than perfect.",
  "Keep building your future step by step.",
  "Every project starts with a first step.",
  "Stay organized. Stay motivated.",
  "Learning never stops.",
  "One task completed is still progress.",
  "Consistent effort changes everything.",
  "You become what you repeatedly do.",
  "Keep going. Your future self is watching.",
];

export function getRandomPhrase() {
  return motivationalPhrases[
    Math.floor(Math.random() * motivationalPhrases.length)
  ];
}